# Generated by Django 3.2 on 2022-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220430_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
