# Generated by Django 3.2 on 2022-04-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_position_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='name',
        ),
    ]
