# Generated by Django 3.2 on 2022-05-08 11:55

from django.db import migrations, models
import events.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220504_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattendance',
            options={},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=events.models.event.user_directory_path),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='user_pk',
            field=models.CharField(max_length=128),
        ),
    ]
